#!/bin/bash

echo "=========================================="
echo "Portfolio de Arquitecto - Proyecto Completo"
echo "=========================================="
echo ""
echo "📁 Estructura de Carpetas:"
echo ""
tree -L 3 -I 'node_modules|.next|.git' --charset ascii

echo ""
echo "=========================================="
echo "📊 Estadísticas del Proyecto:"
echo "=========================================="
echo ""

# Contar archivos
tsx_files=$(find app -name "*.tsx" | wc -l)
ts_files=$(find app -name "*.ts" | wc -l)
css_files=$(find app -name "*.css" | wc -l)

echo "Archivos TypeScript/TSX: $tsx_files"
echo "Archivos TypeScript: $ts_files"
echo "Archivos CSS: $css_files"
echo ""

# Total de líneas de código
total_lines=$(find app -type f \( -name "*.tsx" -o -name "*.ts" -o -name "*.css" \) -exec wc -l {} + | tail -1 | awk '{print $1}')
echo "Total de líneas de código: $total_lines"
echo ""

echo "=========================================="
echo "🚀 Comandos Disponibles:"
echo "=========================================="
echo ""
echo "npm run dev      - Iniciar servidor de desarrollo (puerto 3000)"
echo "npm run build    - Compilar para producción"
echo "npm start        - Ejecutar servidor de producción"
echo "npm run lint     - Ejecutar ESLint"
echo ""

echo "=========================================="
echo "📱 Páginas Disponibles:"
echo "=========================================="
echo ""
echo "GET  /                    - Página de inicio (Hero + Preview)"
echo "GET  /about               - Página Sobre mí"
echo "GET  /projects            - Índice de proyectos"
echo "GET  /projects/landscape  - Proyectos paisajísticos"
echo "GET  /projects/watercolors - Acuarelas"
echo "GET  /projects/photography - Fotografías"
echo ""

echo "=========================================="
echo "✨ Características Implementadas:"
echo "=========================================="
echo ""
echo "✅ Diseño minimalista y responsivo"
echo "✅ Navegación fija con mobile menu"
echo "✅ Sección Hero con animaciones"
echo "✅ Preview de proyectos"
echo "✅ Galería de imágenes (placeholders)"
echo "✅ Sistema de rutas completo"
echo "✅ Componentes reutilizables"
echo "✅ TypeScript para type safety"
echo "✅ Tailwind CSS para estilos"
echo "✅ Animaciones suaves"
echo "✅ SEO optimizado"
echo "✅ Footer con información de contacto"
echo ""

echo "=========================================="
echo "📚 Documentación Disponible:"
echo "=========================================="
echo ""
echo "README.md              - Información general"
echo "README_PORTFOLIO.md    - Documentación del portfolio"
echo "DEVELOPMENT_GUIDE.md   - Guía de desarrollo y customización"
echo ""

echo "=========================================="
echo "🎨 Paleta de Colores:"
echo "=========================================="
echo ""
echo "Primary (Negro):        #000000"
echo "Secondary (Gris oscuro): #1a1a1a"
echo "Accent (Verde oscuro):   #0d3d3d"
echo "Background:             #ffffff"
echo "Text:                   #000000"
echo ""

echo "=========================================="
echo "🔧 Próximos Pasos:"
echo "=========================================="
echo ""
echo "1. Reemplazar placeholders con imágenes reales"
echo "2. Actualizar textos y contenido"
echo "3. Configurar datos de contacto"
echo "4. Agregar formulario de contacto"
echo "5. Implementar CMS o backend"
echo "6. Configurar dominio y SSL"
echo "7. Deploy a Vercel o servidor"
echo ""

echo "=========================================="
echo "✅ Proyecto listo para desarrollo!"
echo "=========================================="
echo ""
